### ISSUE TITLE
to_pandas() fails with None

### ISSUE THREAD

**Issue by elbaro** [ritchie46/polars#336]
A data frame with None fails to call `to_pandas()`.

**Comment by ritchie46** [comment]
You mean with missing values?. Have you got an example?

**Comment by elbaro** [comment]
It seems the problem only happens with boolean.

```
>>> a = pypolars.DataFrame({'col':pypolars.Series([1,2,3])})
>>> a
shape: (3, 1)
╭─────╮
│ col │
│ --- │
│ i64 │
╞═════╡
│ 1   │
├╌╌╌╌╌┤
│ 2   │
├╌╌╌╌╌┤
│ 3   │
╰─────╯
>>> a.shift(2)
shape: (3, 1)
╭──────╮
│ col  │
│ ---  │
│ i64  │
╞══════╡
│ null │
├╌╌╌╌╌╌┤
│ null │
├╌╌╌╌╌╌┤
│ 1    │
╰──────╯
>>> a.shift(2).to_pandas()
   col
0  NaN
1  NaN
2  1.0
```

```
>>> a = pypolars.DataFrame({'col':pypolars.Series([True,False,True])})
>>> a.shift(2).to_pandas()
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', py-polars/src/dataframe.rs:214:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emppu/.local/lib/python3.9/site-packages/pypolars/frame.py", line 213, in to_pandas
    data = self._df.to_pandas_helper()
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Any
```
